[tool.poetry]
name = "dsbunny"
version = "0.1.0"
readme = "README.md"
description = "A bunny for data science"
authors = ["EG"]

[tool.poetry.dependencies]
python = "3.10.7"
pandas = "1.5.*"
pika = "1.3.1"